image:
  file: .gitpod.Dockerfile

ports:
  - port: 1024-6000
    onOpen: ignore

tasks:
  - name: Build Ä Tooling
    init: |
      cd /workspace
      epm init \
       -B https://github.com/e-wrks \
        edh \
       -B http://github.com/complyue \
        nedh els sedh hasdim haskit
      cd /workspace/edh-universe
      stack update
      stack install
      # do HLS a favor
      stack install implicit-hie
      epm x gen-hie > hie.yaml
    command: |
      # stack update
      # cd /workspace/edh-universe
      # epm up
      # stack install
      gp open '/workspace/tour/welcome.edh'

vscode:
  extensions:
    - justusadam.language-haskell@3.3.0:uqgpHstOoamig+7LyFNNVw==
    - haskell.haskell@1.2.0:ZPrUKYpwCCFQf9Q0phszuQ==
    - complyue.edh-vscode-syntax@2.5.3:Y4jCvhkehfu5I7+OU7K0aA==
    - complyue.edh-vscode-formatter@1.6.4:3lWuNSbxPLv55VMhkmgqmw==
    - complyue.edh-vscode-pack@1.0.1:+y6mVWf3H8LSVOu6f7Ud0A==
    - complyue.edh-vscode-lsc@1.0.11:xD4pDUjEsfvH9IyLiXKTqw==
    - complyue.haskit-vscode@0.8.0:3j4qovWtSzNAD+wj9CC8Yw==
