image:
  file: .gitpod.Dockerfile

ports:
  - port: 1024-6000
    onOpen: ignore

tasks:
  - name: Build Ä Tooling
    init: |
      cd /workspace
      epm init \
       -B https://github.com/e-wrks \
        edh \
       -B http://github.com/complyue \
        nedh els sedh hasdim haskit
      cd /workspace/edh-universe
      stack update
      stack install --fast
      # do HLS a favor
      stack install --fast implicit-hie
      epm x gen-hie > hie.yaml
    command: |
      cd /workspace/
      epm up
      # stack update
      stack install
      gp open '/workspace/tour/welcome.edh'
