image:
  file: .gitpod.Dockerfile

ports:
  - port: 1024-6000
    onOpen: ignore

tasks:
  - name: Build Ä Tooling
    init: |
      cd /workspace
      epm init \
       -B https://github.com/e-wrks \
        edh \
       -B http://github.com/complyue \
        nedh els sedh hasdim haskit
      cd /workspace/edh-universe
      stack update
      stack install
      # do HLS a favor
      stack install implicit-hie
      epm x gen-hie > hie.yaml
    command: |
      stack update
      cd /workspace/edh-universe
      epm up
      stack install
      gp open '/workspace/tour/welcome.edh'

vscode:
  extensions:
    - justusadam.language-haskell
    - haskell.haskell
    - complyue.edh-vscode-syntax
    - complyue.edh-vscode-formatter
    - complyue.edh-vscode-pack
    - complyue.edh-vscode-lsc
    - complyue.haskit-vscode
